# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
