# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Rooms',
        ),
        migrations.RenameModel(
            old_name='RoomType',
            new_name='RoomTypes',
        ),
    ]
