# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170919_2121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='RoomTypes',
            new_name='RoomType',
        ),
    ]
