# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170919_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.IntegerField(unique=True),
        ),
    ]
