# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170920_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
